### ISSUE TITLE
inject `TARGET_ONE_HOST` in `app_a` for customization

### ISSUE THREAD

**Issue by larrycai** [blueswen/fastapi-jaeger#3]
````yaml
services:
  app-a:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/fastapi_jaeger:/app
    environment:
      TARGET_ONE_HOST: "fastapi-jaeger_app-b_1"
      TARGET_TWO_HOST: "fastapi-jaeger_app-c_1"
````

In the `docker-composer.yaml`, it is better to inject above configurations (`TARGET_ONE_HOST` & `TARGET_TWO_HOST`

related with #2 (`app_b` could be good enough)
